### ISSUE TITLE
训练权重

### ISSUE THREAD

**Issue by wangmingaaaaa** [XMed-Lab/EPL_SemiDG#3]
您好，我想用您的训练后的权重复现一下您的实验结果，您公布的是百分之2和百分之5训练数据的权重，按道理说应该是M&MS数据集的啊，但为什么最后经过证明我认为是SCGM数据集的权重。SCGM是用的百分之20的数据，所以这个权重到底是哪个数据集的呢？可以解答一下吗？

**Comment by nekomiao123** [comment]
确实是M&MS数据集的权重，你用inference的code去load一下模型，最后的结果应该和论文中是相差无几的
