### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by xiaoxiaoma111** [XMed-Lab/EPL_SemiDG#4]
Hello, I would like to ask how the M&M dataset is downloaded? I found the designated website, but I ran into some difficulties. Is there any other way to download?

**Comment by nekomiao123** [comment]
You need to get the access from the website, and then you can download the dataset

<img width="924" alt="image" src="https://github.com/xmed-lab/EPL_SemiDG/assets/34064940/65e53ec6-50ce-48da-9731-604b99b34bcc">
