### ISSUE TITLE
只用有标签数据和有标签数据无标签数据都用的实验效果差别

### ISSUE THREAD

**Issue by wangmingaaaaa** [XMed-Lab/EPL_SemiDG#5]
您好，我想问下，只用有标签数据和有标签数据无标签数据都用这两者在您的实验中效果差别大吗？我跑了您给的代码，设定了种子数，我对上面这两种情况进行了实验，发现在SCGM数据集的D域中两者测试准确率只相差0.04，在A域的实验中有标签数据无标签数据都用比只用有标签数据的效果还差。我想问下这是什么原因呢？

**Comment by nekomiao123** [comment]
你好，我没有在SCGM数据集上做过这个实验，之前直接follow了前人的setting，只跑过20% label的情况。根据你的发现，分析原因的话，应该是这个数据集比较小，也比较简单（二分类），所以20%的label已经让模型学得挺好的了。建议你可以在MMS那个数据集上做实验，相对来说会比较有提升空间。

**Comment by wangmingaaaaa** [comment]
好的，非常感谢。
