### ISSUE TITLE
种子数

### ISSUE THREAD

**Issue by wangmingaaaaa** [XMed-Lab/EPL_SemiDG#6]
您好，我看了您的代码，在训练和测试的代码中您都设置了种子数，但是对于训练代码，用同一个种子数的情况下重复多次实验得到的不同权重进行测试，最终得到的测试结果是不同的，我想问一下，为什么设置了种子数但是多次训练得到的结果不同呢？我猜想是不是这个原因：upsample_bilinear2d_backward_out_cuda does not have a deterministic implementation，另外，您在论文中得到的实验结果是多次实验得到的平均值吗？

**Comment by wangmingaaaaa** [comment]
我之前问了您关于只用有标签数据和有标签无标签数据都用这两种情况下，有标签无标签数据都用比只用有标签数据模型的性能是否有提高，我想通过固定种子数来做，但是发现种子数相同，但是每次的实验结果是不同的，这样我就没有办法比对加上无标签数据模型性能是否真的提高了，我想问下在M&MS数据集中您做这部分验证的时候是怎么做的呢？

**Comment by nekomiao123** [comment]
> 您好，我看了您的代码，在训练和测试的代码中您都设置了种子数，但是对于训练代码，用同一个种子数的情况下重复多次实验得到的不同权重进行测试，最终得到的测试结果是不同的，我想问一下，为什么设置了种子数但是多次训练得到的结果不同呢？我猜想是不是这个原因：upsample_bilinear2d_backward_out_cuda does not have a deterministic implementation，另外，您在论文中得到的实验结果是多次实验得到的平均值吗？

估计是你的种子数没有设定全，你可以参考使用accelerate库里面的设定方法，比如:
```
from accelerate import set_seed
set_seed(42)
```

**Comment by nekomiao123** [comment]
> 我之前问了您关于只用有标签数据和有标签无标签数据都用这两种情况下，有标签无标签数据都用比只用有标签数据模型的性能是否有提高，我想通过固定种子数来做，但是发现种子数相同，但是每次的实验结果是不同的，这样我就没有办法比对加上无标签数据模型性能是否真的提高了，我想问下在M&MS数据集中您做这部分验证的时候是怎么做的呢？

其实一般来说，种子数对实验效果的影响并没有那么大，也许不到一个点。我在做M&MS那个数据集的时候，提升比较明显，所以我也没那么在意种子的问题，我建议还是你可以多跑几次实验，平均一下。关于种子的设定问题也可以参考一下我上面发的代码。

**Comment by wangmingaaaaa** [comment]
我按照您说的from accelerate import set_seed
set_seed(42)的方法设置了种子数，但第一次训练和第二次训练在相同的epoch下，得到的loss和dice还是有一些偏差，这种情况是属于正常吗？

**Comment by nekomiao123** [comment]
> 我按照您说的from accelerate import set_seed set_seed(42)的方法设置了种子数，但第一次训练和第二次训练在相同的epoch下，得到的loss和dice还是有一些偏差，这种情况是属于正常吗？

如果偏差不大的话，应该不是大问题。但是按理来说，设定了种子数就应该没有偏差，可能还是有哪个地方存在一些随机性。

**Comment by wangmingaaaaa** [comment]
好的，非常感谢。
