### ISSUE TITLE
backbone

### ISSUE THREAD

**Issue by wangmingaaaaa** [XMed-Lab/EPL_SemiDG#7]
Hello, I see that your code comparison articles are all based on unet as the backbone, but your article is based on resnet50 as the backbone. Is it unfair to compare with different backbones?

**Comment by nekomiao123** [comment]
The code is based on CPS code, so I follow the CPS using resnet50 as the backbone. Then I noticed this, so I also did the Unet experiments. The experiments show that the method is still useful.
![image](https://github.com/xmed-lab/EPL_SemiDG/assets/34064940/95ce3433-406a-4c15-a962-0dffb5a9553b)

**Comment by wangmingaaaaa** [comment]
Thank you very much for your reply. I also tried changing the backbone in your code to unet but it didn't achieve your effect. If it's convenient, can you share your code for using unet as the backbone? This is my email 17598037963@163.com

**Comment by wangmingaaaaa** [comment]
When using unet as backbone, do you use pretrained weights?

**Comment by nekomiao123** [comment]
No, you can use the "normalUnet" in my code.

**Comment by nekomiao123** [comment]
> When using unet as backbone, do you use pretrained weights?

No, you can use the "normalUnet" in my code.
